cam_model: Pinhole
cam_width:  848
cam_height: 480
cam_fx: 426.551167166986
cam_fy: 426.6142447926181
cam_cx: 429.1314081919893
cam_cy: 247.64043896840604
cam_d0: -0.04198021932360902
cam_d1: 0.0321572425855278
cam_d2: -0.0007393654683384666
cam_d3: 0.0008216736756188225